version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8006:8000"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=cryptodb
      - POSTGRES_USER=akreem
      - POSTGRES_PASSWORD=korbaca2013
  